### ISSUE TITLE
how to show % completed

### ISSUE THREAD

**Issue by lahela223** [Toqe/Downloader#1]
hi 
i would like to thankyout for creating this awesome library. i need to show some % to user how much its downloaded. can you please guide me how to do that i am following your multipart downlaod
thankyou

**Comment by Toqe** [comment]
My pleasure.
I've added a `DownloadProgressMonitor` class which you can use for this purpose. Please also have a look at the newly created `Downloader.Example` project, it will demonstrate you the use of it. Just replace the `url` variable with the url of a larger file and watch it in action.

**Comment by lahela223** [comment]
absolutely fantastic. now can you please tell me what license it have can i use in my application??

**Comment by Toqe** [comment]
Absolutely, it's under MIT license, have a look at the [LICENSE](https://github.com/Toqe/Downloader/blob/master/LICENSE) file. You can use this software in any way you like as long as you include the original license in some way into your application. For example you can have a textfile, a dialog or a link to your website, where all third party components your application uses are listed with the respective license.
