### ISSUE TITLE
WebForm can not trigger the registered event

### ISSUE THREAD

**Issue by dazhuangtage** [Toqe/Downloader#10]
The code is as follows:
 public string SaveFile(HttpContext context = null, bool immediateSave = true)
        {
            var url = new Uri(GetFileRemoteUrl());
            var requestBuilder = new SimpleWebRequestBuilder();
            var dlChecker = new DownloadChecker();
            var httpDlBuilder = new SimpleDownloadBuilder(requestBuilder, dlChecker);
            var timeForHeartbeat = 3000;
            var timeToRetry = 5000;
            var maxRetries = 5;
            var resumingDlBuilder = new ResumingDownloadBuilder(timeForHeartbeat, timeToRetry, maxRetries, httpDlBuilder);
            List<DownloadRange> alreadyDownloadedRanges = null;
            var bufferSize = 4096000;
            var numberOfParts = 4;
            var download = new MultiPartDownload(url, bufferSize, numberOfParts, resumingDlBuilder, requestBuilder, dlChecker, alreadyDownloadedRanges);
            download.DownloadCompleted += Download_DownloadCompleted;
            download.Start();
            while ( !dlSaver.Complete )
            {
                Thread.Sleep(1000);
            }
            if ( dlSaver.IsError )
            {
                throw dlSaver.Exception;
            }
            return dlSaver.FilePath;
        }

        
       ///This is always triggered
         
        private void Download_DownloadCompleted(Toqe.Downloader.Business.Contract.Events.DownloadEventArgs args)
        {

            args.Download.DetachAllHandlers();
        }

The console is no problem, what is the problem?

**Comment by Toqe** [comment]
Sorry, but this is no problem directly correlated to Downloader.
It seems like you've modified the dlSaver so I can't reproduce the behaviour.
I've used the following very simple WebForms page and it worked fine:

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Toqe.Downloader.Business.Download;
using Toqe.Downloader.Business.DownloadBuilder;
using Toqe.Downloader.Business.Observer;
using Toqe.Downloader.Business.Utils;

namespace WebApplication1
{
    public partial class _Default : Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
        }

        private bool isCompleted = false;

        protected void Button1_Click(object sender, EventArgs e)
        {
            var url = new Uri("http://ftp.uni-kl.de/pub/linux/knoppix/KNOPPIX_V7.2.0bootonly-2013-06-16-DE.iso");
            var file = new System.IO.FileInfo("d:\\knoppix.iso");
            var requestBuilder = new SimpleWebRequestBuilder();
            var dlChecker = new DownloadChecker();
            var httpDlBuilder = new SimpleDownloadBuilder(requestBuilder, dlChecker);
            var timeForHeartbeat = 3000;
            var timeToRetry = 5000;
            var maxRetries = 5;
            var resumingDlBuilder = new ResumingDownloadBuilder(timeForHeartbeat, timeToRetry, maxRetries, httpDlBuilder);
            List<Toqe.Downloader.Business.Contract.DownloadRange> alreadyDownloadedRanges = null;
            var bufferSize = 4096000;
            var numberOfParts = 4;
            var download = new MultiPartDownload(url, bufferSize, numberOfParts, resumingDlBuilder, requestBuilder, dlChecker, alreadyDownloadedRanges);
            var dlSaver = new DownloadToFileSaver(file);
            dlSaver.Attach(download);
            download.DownloadCompleted += Download_DownloadCompleted;
            this.isCompleted = false;
            download.Start();

            while (!this.isCompleted)
            {
                Thread.Sleep(1000);
            }

            // if (dlSaver.IsError)
            // {
            // You should never throw an already catched exception because you will lose all the stacktrace.
            // Always encapsulate it into a new exception
            // throw new InvalidOperationException(dlSaver.Exception);
            // return null;
            // }

            // return file.FullName;

            Console.WriteLine("finished");
        }

        private void Download_DownloadCompleted(Toqe.Downloader.Business.Contract.Events.DownloadEventArgs args)
        {
            args.Download.DetachAllHandlers();
            this.isCompleted = true;
        }
    }
}
```

I can only guess, but if you want to do an asynchronous notification to the user when the download has finished, that can't be done with standard HTTP or WebForms that easily. Please have a look at for example at [this SO question](http://stackoverflow.com/questions/7759095/asp-net-how-to-update-a-page-upon-a-click-event-of-another-page)

One more remark:
It's not a good practice to use `throw dlSaver.Exception;` as you will lose the original stack trace of the exception, which can be very helpful when hunting for bugs. You should always encapsulate the original exception into a new exception and throw that on, for example `throw new InvalidOperationException(dlSaver.Exception);`

**Comment by dazhuangtage** [comment]
Thank you very much for your reply, I am trying to write a demo.
