### ISSUE TITLE
More instances of Downloader

### ISSUE THREAD

**Issue by Dolus1984** [Toqe/Downloader#11]
I want to download two files at same time so i created two threads of Downloader.
I am unable in any way to start more than one thread of Downloader in same time.
After starting second one it just stay at 0% and do not open connection until first thread is finished.
I even tried to rename all variables and create separated void but result was same.
I noticed that if `numberOfParts ` is set to 1 i can start second thread at same time and it downloading fine.

**Comment by Toqe** [comment]
Please have a look at [this StackOverflow question](http://stackoverflow.com/questions/1361771/max-number-of-concurrent-httpwebrequests).
Maybe that's the limititation you're running into.
Please let me know if one of the options (` System.Net.ServicePointManager.DefaultConnectionLimit` or app.config `connectionManagement` element) work for you, maybe I can then put a hint in the README.

**Comment by Dolus1984** [comment]
`System.Net.ServicePointManager.DefaultConnectionLimit` resolved this issue!
Thank you for this suggestion. Would be good to have it updated on Git.

**Comment by Toqe** [comment]
Ok, I've updated the README.
