### ISSUE TITLE
this software  can  user for product ？

### ISSUE THREAD

**Issue by fancyecommerce** [Toqe/Downloader#14]
this software  can  user for product ？

**Comment by Toqe** [comment]
Absolutely, it's under MIT license, have a look at the [LICENSE](https://github.com/Toqe/Downloader/blob/master/LICENSE) file. You can use this software in any way you like as long as you include the original license in some way into your application. For example you can have a textfile, a dialog or a link to your website, where all third party components your application uses are listed with the respective license.
