### ISSUE TITLE
Help! Content-Length is missing or -1, but transfer encoding is set to chunked

### ISSUE THREAD

**Issue by videoguy** [Toqe/Downloader#19]
Does this lib work with web servers that don't provide Content-Length, but respond with chunked encoding?
The content-length is either missing or set to -1, but transfer-encoding header comes with value "chunked".

Thanks

**Comment by Toqe** [comment]
You can use the `SimpleDownloadBuilder` with chunked responses, but you won't be able to resume or multi-part download such a response with this library. My knowledge about chunked transfers isn't so deep so I'm not quite sure if it is possible support resumes as chunked downloads are usually used when the final size isn't known ahead.
