### ISSUE TITLE
Some download url (such as: github zip) will not get response

### ISSUE THREAD

**Issue by jzlhll** [Toqe/Downloader#20]
Such as https://github.com/Toqe/Downloader/archive/master.zip, when I start downloading this uri.
It will get exception.
Because those links cannot get response, it will crash in CheckDownload(Uri url, IWebRequestBuilder requestBuilder) .

**Comment by Toqe** [comment]
I can confirm your problem.

```c#
System.Net.WebException: Die zugrunde liegende Verbindung wurde geschlossen: Unerwarteter Fehler beim Senden.. ---> System.IO.IOException: Unerwartetes Dateiende oder 0 Bytes vom Transportstream erhalten.
   bei System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   bei System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   bei System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   bei System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   bei System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   bei System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   bei System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   bei System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Net.HttpWebRequest.GetResponse()
   bei Toqe.Downloader.Business.Utils.DownloadChecker.CheckDownload(Uri url, IWebRequestBuilder requestBuilder) in D:\dev\Downloader\Downloader.Business\Utils\DownloadChecker.cs:Zeile 28.
```

Changing the .NET Framework version of the Downloader projects to (for example) .NET 4.7.2 solves the problem (but creates a follow up problem: GitHub doesn't support resuming).

**Comment by jzlhll** [comment]
Resume is no matter.But how i can solve it on .net 4.5. Does it must change to 4.7.2? Maybe I should try donot **checkDownload** or directly set checkDownload result to seccuss with those uri(github zip)?

**Comment by Toqe** [comment]
I think the problem is due to the support of HTTP (and/or its features) in the used .NET Framework, although I don't have the time to examine the exact problem at the moment. Please use at least .NET Framework 4.6.2 to solve this.

**Comment by jzlhll** [comment]
I find the lower net framework could make it no exception when **getResponse**.

> ServicePointManager.ServerCertificateValidationCallback = new RemoteCertificateValidationCallback(CheckValidationResult);
>             ServicePointManager.ServerCertificateValidationCallback += (s, cert, chain, sslPolicyErrors) => true;
>             ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

> private static bool CheckValidationResult(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors errors)
>         {
>             return true;
>         }
> 

Now, let's compact those uris. 
Maybe those uris, **response.Headers["Accept-Ranges"] = null** && **response.ContentLength = -1**, we should compact it those case.

**Comment by Toqe** [comment]
I think you shouldn't disable the validation of the server certificate, that will make you vulnerable to Man-in-the-middle attacks.
