### ISSUE TITLE
Resuming download after restart application

### ISSUE THREAD

**Issue by Dolus1984** [Toqe/Downloader#3]
Is there any way for resume downloading file after restart of application without starting from scratch?
This issue may appear when downloading big files due to reaching reconnect limit or closing application.
I assume need to provide `alreadyDownloadedRanges` but how to access it based on existing file?

**Comment by Toqe** [comment]
Please have a look at issue #2.

Basically you need to access the `AlreadyDownloadedRanges` property of the `MultiPartDownload` object you are using. You can for example serialize this to a file when closing your application. On Restart just deserialize it and provide it to the constructor of `MultiPartDownload`.

**Comment by Dolus1984** [comment]
I already saw issue #2 
I suspected that it can be done by serialization and deserialization,
Sadly there are unexpected behaviors which may prevent you using such method by users like unexpected shutdown, so your serialized object does not fit with file content if i am right.
It would be good to use `AddRange` but i believe it does not really fit with your multi-part concept.
I previously used java based app (JDownloader) which was capable to resume multi-part downloading after restarting app.

**Comment by Toqe** [comment]
I'm not quite sure if I understand your point correctly, but I think events like sudden shutdown could be handled by not only saving the state of a download when stopping it gracefully, but also saving it from time to time. It's also no problem if the saved state is a bit older than the already downloaded file, as the resumed download would only overwrite some already downloaded parts which causes not trouble.

If you really want to be sure that the download on the disk is matching the state of the already downloaded parts, you could write your own version of `DownloadToFileSaver`, which stores the state to a file placed beside the target file as soon as `DataReceived` is called. Drawback of this solution would be additional disk throughput, so you may have to throttle the writes of the state to disk.

**Comment by Dolus1984** [comment]
You are right, i missed that already downloaded parts will be overwritten.
I properly deserialized `AlreadyDownloadedRanges` to file and serialized it back, so it resumed much faster than by `AddRange` request.
Thank you for this suggestion.
