### ISSUE TITLE
Remaining time

### ISSUE THREAD

**Issue by Dolus1984** [Toqe/Downloader#6]
Is it possible to add calculation of remaining time, so user can see how much time left based on approx download speed connection?

**Comment by Toqe** [comment]
You can add this by using the `DownloadProgressMonitor` and `DownloadSpeedMonitor` and calculate it with both their values. Have a look at the modified example in Program.cs:

```C#
var remainingTime = (progressMonitor.GetTotalFilesizeInBytes(download) - progressMonitor.GetCurrentProgressInBytes(download)) / speedMonitor.GetCurrentBytesPerSecond();
Console.WriteLine("Remaining time: " + remainingTime + " sec.");
```

**Comment by Dolus1984** [comment]
This answer was really helpful.
Thank you.

**Comment by Dolus1984** [comment]
Please be aware that `/ speedMonitor.GetCurrentBytesPerSecond()` in case when connecting estabilishing take some time (slow connections / firewall popoup which require use reaction) may come with 0 value what throw `System.DivideByZeroException` unhandled exception for this math operation.
