### ISSUE TITLE
Download speed limiting

### ISSUE THREAD

**Issue by Dolus1984** [Toqe/Downloader#7]
Did you ever considered to implement some trigger or variable which would allow user to control download speed? Multi-part downloader due to way of how is working is supposed to maximize download speed, but at same time can consume completly user bandwitch. That would be nice feature.

**Comment by Toqe** [comment]
As the calls to the `DataReceived` event subscribers are synchronous, this can be achieved by just delaying the return of the event handler to the event invoker. Basically that's done in the `DownloadThrottling` class with the same basic statistics as in `DownloadSpeedMonitor`.

You can use it like this, if you want to limit your download to for example 200 KiB/second:
```C#
var downloadThrottling = new DownloadThrottling(maxBytesPerSecond: 200 * 1024, maxSampleCount: 128);
downloadThrottling.Attach(download);
```

**Comment by Dolus1984** [comment]
I am not sure why when i set this value on `DownloadSpeedMonitor` it sometimes going much over declared value but anyway your answer helped me with enabling possibility to control bandwitch of Downloader.
Thank you
