### ISSUE TITLE
Download speed calculation intervals

### ISSUE THREAD

**Issue by Dolus1984** [Toqe/Downloader#8]
Current download speed calculations are performed very often, what effect very high peaks up and down not really depend of how internet connection stable is. 
Would be good to be able to control time for which average download speed is calculated.
I had a thought to sum up download speed every tick (1s) and ticks in while loop since its exact one second and then divide it but i maybe its better to do something directly in `DownloadSpeedMonitor` class for this.

**Comment by Toqe** [comment]
The `DownloadSpeedMonitor` is an example of how this can be theoretically achieved. Of course you can collect a larger number of samples or build your own which uses a different statistical sampling method to make the result more fitting for your application's requirements.
